### ISSUE TITLE
the testing set

### ISSUE THREAD

**Issue by hezw2016** [jinyeying/RaindropClarity#1]
Hey,
thank you for sharing your wonderful work.
do you have a plan to share the testing set?

**Comment by jinyeying** [comment]
> Hey, thank you for sharing your wonderful work. do you have a plan to share the testing set?

yes, we plan to hold a workshop. after the workshop, we will release it.

**Comment by hezw2016** [comment]
What is the name of the workshop? I guess it will be held on ECCV. Maybe we can talk in Milan.

**Comment by jinyeying** [comment]
> What is the name of the workshop? I guess it will be held on ECCV. Maybe we can talk in Milan.

sure, I have released the test set without ground truth. The full version will be released after the workshop.

**Comment by hezw2016** [comment]
thank you very much.
It is a wonderful work and will help the whole community.

**Comment by jinyeying** [comment]
> What is the name of the workshop? I guess it will be held on ECCV. Maybe we can talk in Milan.

Due to a scheduling conflict, I regret that I will not be able to attend ECCV in Milan. We are still in the process of applying for the dataset workshop. Once the application is successful, I will provide an update.

**Comment by jinyeying** [comment]
The CVPR workshop is available at https://codalab.lisn.upsaclay.fr/competitions/21345
