### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/sda/lxy/RaindropClarity/datasets/DayRainDrop_Test/Clear/00001'

### ISSUE THREAD

**Issue by xuanyili97** [jinyeying/RaindropClarity#5]
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/sda/lxy/RaindropClarity/datasets/DayRainDrop_Test/Clear/00001'

**Comment by jinyeying** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/mnt/sda/lxy/RaindropClarity/datasets/DayRainDrop_Test/Clear/00001'

因为我们打算办一个workshop的比赛, Clear的图片目前没有release, 但是应该不影响跑出来测试结果
